### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by chriskrycho** [tracked-tools/ember-async-data#455]
- [x] #473
- [x] drop old Node and TS versions
    - [x] #526
    - [ ] #527
    - [x] #572
    - [x] #576

**Comment by SergeAstapov** [comment]
@chriskrycho #527 and #526 should address point 4

**Comment by chriskrycho** [comment]
I've updated my thinking slightly: I'm going to punt the `@dependentKeyCompat` and `assert` for `.value` and unsafe `.error` access to a 2.0 (presumably later in the year) with deprecations introduced now so people can use deprecation workflow to tackle them (see #575). That way we can cut 1.0 *now*, requiring the context argument, and then *later* make the second set of breaking changes, while giving people a path to opt into that with regression-prevention via deprecation workflow. 🚀 Accordingly, I'm going to extract those two items to a new 2.0 tracking issue and close this with a 1.0 release in short order!

**Comment by chriskrycho** [comment]
Closed: [v1.0.0](https://github.com/tracked-tools/ember-async-data/releases/tag/v1.0.0)! 🎉 See #577 to track the remaining two issues.
